#ifndef CONFIG_H
#define CONFIG_H

// Device Configuration
#define DEVICE_NAME "SmartChessboard MKR"
#define DEVICE_VERSION "1.0.0"

// WiFi Configuration
#define CHESSBOARD_TCP_PORT 8080
#define WIFI_TIMEOUT_MS 20000
#define WIFI_MAX_RETRIES 20

// Hardware Pin Configuration
#define LED_PIN 2
#define HAPTIC_PIN 4
#define STATUS_LED_PIN 5

// Sensor Configuration (8x8 chessboard)
#define BOARD_SIZE 8
#define TOTAL_SQUARES 64
#define SENSOR_READ_DELAY 50
#define MOVE_DETECTION_THRESHOLD 100

// LED Patterns
#define LED_PATTERN_MOVE_HIGHLIGHT "MOVE_HIGHLIGHT"
#define LED_PATTERN_CHECK "CHECK"
#define LED_PATTERN_CHECKMATE "CHECKMATE"
#define LED_PATTERN_LAST_MOVE "LAST_MOVE"
#define LED_PATTERN_ERROR "ERROR"

// Haptic Patterns
#define HAPTIC_PATTERN_MOVE "MOVE"
#define HAPTIC_PATTERN_CAPTURE "CAPTURE"
#define HAPTIC_PATTERN_CHECK "CHECK"
#define HAPTIC_PATTERN_ERROR "ERROR"

// Message Types
#define MSG_TYPE_WIFI_CONFIG "WIFI_CONFIG"
#define MSG_TYPE_WIFI_STATUS "WIFI_STATUS"
#define MSG_TYPE_MOVE_DETECTED "MOVE_DETECTED"
#define MSG_TYPE_MOVE_CONFIRM "MOVE_CONFIRM"
#define MSG_TYPE_GAME_STATE "GAME_STATE"
#define MSG_TYPE_LED_CONTROL "LED_CONTROL"
#define MSG_TYPE_HAPTIC_FEEDBACK "HAPTIC_FEEDBACK"
#define MSG_TYPE_PING "PING"
#define MSG_TYPE_PONG "PONG"
#define MSG_TYPE_ERROR "ERROR"
#define MSG_TYPE_DEVICE_INFO "DEVICE_INFO"
#define MSG_TYPE_SETUP_STATUS "SETUP_STATUS"

// WiFi Status Message Types
#define MSG_TYPE_WIFI_STATUS "WIFI_STATUS"
#define MSG_TYPE_WIFI_SUCCESS "WIFI_SUCCESS"
#define MSG_TYPE_WIFI_ERROR "WIFI_ERROR"

// Error Codes
#define ERROR_WIFI_CONNECTION_FAILED "WIFI_CONNECTION_FAILED"
#define ERROR_INVALID_MOVE "INVALID_MOVE"
#define ERROR_SENSOR_ERROR "SENSOR_ERROR"
#define ERROR_LED_ERROR "LED_ERROR"
#define ERROR_HAPTIC_ERROR "HAPTIC_ERROR"
#define ERROR_INVALID_MESSAGE "INVALID_MESSAGE"
#define ERROR_TIMEOUT "TIMEOUT"
#define ERROR_DEVICE_NOT_FOUND "DEVICE_NOT_FOUND"
#define ERROR_SETUP_FAILED "SETUP_FAILED"

// Setup Status Codes
#define SETUP_STATUS_CONNECTING "CONNECTING"
#define SETUP_STATUS_CONFIGURING_WIFI "CONFIGURING_WIFI"
#define SETUP_STATUS_COMPLETED "COMPLETED"
#define SETUP_STATUS_FAILED "FAILED"

// WiFi Status Codes
#define WIFI_STATUS_CONNECTING "connecting"
#define WIFI_STATUS_CONNECTED "connected"
#define WIFI_STATUS_SUCCESS "success"
#define WIFI_STATUS_ERROR "error"

// Timing Configuration
#define PING_INTERVAL_MS 30000
#define MOVE_SIMULATION_INTERVAL_MS 30000
#define LED_BLINK_DURATION_MS 200
#define HAPTIC_DEFAULT_DURATION_MS 100

// Debug Configuration
#define DEBUG_MODE true
#define SERIAL_BAUD_RATE 115200

// Memory Configuration
#define JSON_BUFFER_SIZE 2048
#define MAX_MESSAGE_LENGTH 1024
#define MAX_SSID_LENGTH 32
#define MAX_PASSWORD_LENGTH 64

// WiFi credentials are now stored in wifi_config.h file

// Default Game State
#define DEFAULT_FEN "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
#define DEFAULT_PLAYER "White"

#endif // CONFIG_H

